name: Secret Manager

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get local.properties from secrets
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties
